# This is a basic workflow to help you get started with Actions

name: rootfs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kernel:
    runs-on: ubuntu-24.04-arm
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential bc flex bison 7zip kmod bash cpio binutils tar git wget dpkg libssl-dev systemd-ukify systemd-boot-efi

      - name: Setup SSL Files
        shell: bash
        run: |
          # Decode and store key
          echo "${{ secrets.SECURE_BOOT_KEY }}" | base64 -d > sb.key
          # Decode and store certificate
          echo "${{ secrets.SECURE_BOOT_CERTIFICATE }}" | base64 -d > sb.crt
          # Set correct permissions
          chmod 600 sb.key
          chmod 644 sb.crt

      - name: Build kernel
        run: sudo bash nabu-kernel_build.sh

      - name: Upload deb packages
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: xiaomi-nabu-debs
          path: ${{ github.workspace }}/*.deb

      - name: Upload UKI (EFI Image)
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: unified_kernel_image
          path: ${{ github.workspace }}/linux-xiaomi-nabu/boot/efi/EFI/ubuntu/*.efi
          
  rootfs:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04-arm
    needs: kernel
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: xiaomi-nabu-debs*
      - name: Install Dependencies
        run: sudo apt update && sudo apt install unzip build-essential bc flex bison kmod bash cpio binutils tar git wget dpkg libssl-dev android-sdk-libsparse-utils

      - name: Build rootfs
        run: sudo bash nabu-rootfs_build.sh

      - name: Upload rootfs for dd
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: rootfs_dd
          path: rootfs.img.xz
          compression-level: 0

      - name: Upload rootfs for fastboot
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: rootfs_fastboot
          path: rootfs.sparse.img.xz
          compression-level: 0

      - name: Upload esp for dd
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: esp_dd
          path: esp.img.xz
          compression-level: 0

      - name: Upload esp for fastboot
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: esp_fastboot
          path: esp.sparse.img.xz
          compression-level: 0
